POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_HISTORY_BACKGROUND='green'
POWERLEVEL9K_SHORTEN_STRATEGY="none"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{012}❯ "

# Prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs kubecontext azure terraform)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# Show on Command
POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform'
POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
#POWERLEVEL9K_TERRAFORM_SHOW_ON_COMMAND='terraform'

# Dir
POWERLEVEL9K_DIR_BACKGROUND='208'
#POWERLEVEL9K_DIR_CLASSES=()

# VCS
POWERLEVEL9K_VCS_BACKGROUND='070'

# Kubecontext
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='019'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='015'

# Azure
POWERLEVEL9K_AZURE_ICON='\UF0805'
POWERLEVEL9K_AZURE_BACKGROUND=074
POWERLEVEL9K_AZURE_FOREGROUND=015

# User
DEFAULT_USER='jeffrey'
