POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_HISTORY_BACKGROUND='green'
POWERLEVEL9K_SHORTEN_STRATEGY="none"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context user dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history kubecontext)

POWERLEVEL9K_KUBECONTEXT_BACKGROUND='004'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='000'

DEFAULT_USER='jeffrey'