POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_HISTORY_BACKGROUND='green'
POWERLEVEL9K_SHORTEN_STRATEGY="none"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{012}❯ "

# Prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(kubecontext azure)

# Show on Command
POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform'
POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'

# Kubecontext
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='026'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='015'

# Azure
POWERLEVEL9K_AZURE_ICON='\UF0805'
POWERLEVEL9K_AZURE_BACKGROUND=033
POWERLEVEL9K_AZURE_FOREGROUND=015

# User
DEFAULT_USER='jeffrey'
